# k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: <your-api-image-name> # Update with your API image name
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              value: "mongodb://db:27017/dfsa"  # Use the service name for internal communication
