apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "backend-monitor"
        static_configs:
          - targets: ["backend-service.default.svc.cluster.local:8000"]
      - job_name: "client-monitor"
        static_configs:
          - targets: ["client.default.svc.cluster.local:5173"]