# backend-deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ishrakadit07/mern-docker-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-password
            - name: MONGODB_CLUSTER_NAME
              value: "cluster-for-ishrak"
            - name: MONGODB_APP_NAME
              value: "cluster-for-ishrak"
          resources:               # Add this block for resource requests and limits
            requests:
              cpu: "200m"          # CPU request, adjust based on your app's needs
              memory: "256Mi"      # Memory request
            limits:
              cpu: "500m"          # CPU limit
              memory: "512Mi"      # Memory limit
---
# backend-service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 8000
  type: LoadBalancer
---
# client-deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ishrakadit07/mern-docker-web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://144.126.240.66:8000"
          resources:               # Add this block for resource requests and limits
            requests:
              cpu: "200m"          # CPU request
              memory: "256Mi"      # Memory request
            limits:
              cpu: "500m"          # CPU limit
              memory: "512Mi"      # Memory limit
---
# client-service
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 30001
  selector:
    app: client
---
# Horizontal Pod Autoscaler for backend-deploy
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deploy
  minReplicas: 1        
  maxReplicas: 10        
  targetCPUUtilizationPercentage: 80  # Scale when CPU usage exceeds 80%
  #targetMemoryUtilizationPercentage: 75  # Scale when memory usage exceeds 75%
---
# Horizontal Pod Autoscaler for client-deploy
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client 
  minReplicas: 1       
  maxReplicas: 10    
  targetCPUUtilizationPercentage: 80  # Scale when CPU usage exceeds 80%
  #targetMemoryUtilizationPercentage: 75  # Scale when memory usage exceeds 75%